-- ============================================================
-- Campus Connect — patch_v10.sql
-- Applied via MCP on 2026-04-12.
-- ✅ Already applied — do NOT re-run.
-- ============================================================

-- Creates 3 UMaT reference tables:
--   umat_faculties  — 8 faculties/schools
--   umat_programmes — 29 programmes (BSc, Diploma, Certificate)
--   umat_hostels    — 14 hostels (3 main halls + 9 private + 2 other)
--
-- Indexes added:
--   profiles_department_idx ON profiles(department)
--   profiles_hostel_idx     ON profiles(hostel)
--
-- RLS: all 3 tables public SELECT only (read-only reference data)
--
-- Faculties seeded:
--   FMMT (2), FGES (3), FoE (3), FCaMS (5),
--   SPetS (4), FIMS (3), SRID/Essikado (5), Diploma/Cert (4)
--
-- Hostels seeded:
--   main_hall (3): Chamber of Mines, Gold Refinery, K.T. Hall
--   private   (9): Dubai, Hilda, Credit Union, Swag Mansion,
--                  Osborn, Oak, Fijenco, Waterloo, Floger
--   other     (2): Off-Campus, Other
