/**
 * Ghana Universities Registry
 * Complete list of accredited universities in Ghana (43 institutions)
 * Used for multi-university routing: /uni/[slug]/goods, /uni/[slug]/services
 */

export type UniversityType = 'public' | 'private' | 'technical'

export interface GhanaUniversity {
  slug: string          // URL-safe identifier (e.g. "umat", "ug", "knust")
  name: string          // Full official name
  shortName: string     // Common abbreviation (e.g. "UMaT", "UG", "KNUST")
  region: string        // Administrative region
  city: string          // City/town
  type: UniversityType
  website?: string
  established?: number
  colors?: { primary: string; secondary: string }
}

export const GHANA_UNIVERSITIES: GhanaUniversity[] = [
  // ─── Major Public Universities ───────────────────────────────────────────────
  {
    slug: 'ug',
    name: 'University of Ghana',
    shortName: 'UG',
    region: 'Greater Accra',
    city: 'Legon, Accra',
    type: 'public',
    established: 1948,
    website: 'ug.edu.gh',
    colors: { primary: '#002147', secondary: '#DAA520' },
  },
  {
    slug: 'knust',
    name: 'Kwame Nkrumah University of Science and Technology',
    shortName: 'KNUST',
    region: 'Ashanti',
    city: 'Kumasi',
    type: 'public',
    established: 1951,
    website: 'knust.edu.gh',
    colors: { primary: '#006400', secondary: '#FFD700' },
  },
  {
    slug: 'ucc',
    name: 'University of Cape Coast',
    shortName: 'UCC',
    region: 'Central',
    city: 'Cape Coast',
    type: 'public',
    established: 1962,
    website: 'ucc.edu.gh',
    colors: { primary: '#003087', secondary: '#C8A951' },
  },
  {
    slug: 'uds',
    name: 'University for Development Studies',
    shortName: 'UDS',
    region: 'Northern',
    city: 'Tamale',
    type: 'public',
    established: 1992,
    website: 'uds.edu.gh',
    colors: { primary: '#1B5E20', secondary: '#FF6B00' },
  },
  {
    slug: 'uew',
    name: 'University of Education, Winneba',
    shortName: 'UEW',
    region: 'Central',
    city: 'Winneba',
    type: 'public',
    established: 1992,
    website: 'uew.edu.gh',
    colors: { primary: '#6A0DAD', secondary: '#FFD700' },
  },
  {
    slug: 'umat',
    name: 'University of Mines and Technology',
    shortName: 'UMaT',
    region: 'Western',
    city: 'Tarkwa',
    type: 'public',
    established: 2004,
    website: 'umat.edu.gh',
    colors: { primary: '#1B5E20', secondary: '#FFD700' },
  },
  {
    slug: 'uhas',
    name: 'University of Health and Allied Sciences',
    shortName: 'UHAS',
    region: 'Volta',
    city: 'Ho',
    type: 'public',
    established: 2012,
    website: 'uhas.edu.gh',
    colors: { primary: '#00695C', secondary: '#B2DFDB' },
  },
  {
    slug: 'uenr',
    name: 'University of Energy and Natural Resources',
    shortName: 'UENR',
    region: 'Bono',
    city: 'Sunyani',
    type: 'public',
    established: 2013,
    website: 'uenr.edu.gh',
    colors: { primary: '#4E342E', secondary: '#66BB6A' },
  },
  {
    slug: 'ubu',
    name: 'University of Business and Integrated Development Studies',
    shortName: 'UBIDS',
    region: 'Upper West',
    city: 'Wa',
    type: 'public',
    established: 2021,
    colors: { primary: '#1565C0', secondary: '#FFD700' },
  },
  {
    slug: 'aamusted',
    name: 'Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development',
    shortName: 'AAMUSTED',
    region: 'Ashanti',
    city: 'Kumasi',
    type: 'public',
    established: 2020,
    website: 'aamusted.edu.gh',
    colors: { primary: '#1A237E', secondary: '#FFD700' },
  },
  {
    slug: 'cstutas',
    name: 'C.K. Tedam University of Technology and Applied Sciences',
    shortName: 'CKT-UTAS',
    region: 'Upper East',
    city: 'Navrongo',
    type: 'public',
    established: 2020,
    website: 'cktsutas.edu.gh',
    colors: { primary: '#B71C1C', secondary: '#FFD700' },
  },
  {
    slug: 'sjtu-ghana',
    name: 'SD Dombo University of Business and Integrated Development Studies',
    shortName: 'SDD-UBIDS',
    region: 'Upper West',
    city: 'Wa',
    type: 'public',
    established: 2021,
    colors: { primary: '#4A148C', secondary: '#FFD700' },
  },

  // ─── Technical Universities (Public) ─────────────────────────────────────────
  {
    slug: 'accra-tu',
    name: 'Accra Technical University',
    shortName: 'ATU',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'technical',
    established: 1949,
    website: 'atu.edu.gh',
    colors: { primary: '#1565C0', secondary: '#FFC107' },
  },
  {
    slug: 'kumasi-tu',
    name: 'Kumasi Technical University',
    shortName: 'KsTU',
    region: 'Ashanti',
    city: 'Kumasi',
    type: 'technical',
    established: 1954,
    website: 'kstu.edu.gh',
    colors: { primary: '#880E4F', secondary: '#FFD700' },
  },
  {
    slug: 'cape-coast-tu',
    name: 'Cape Coast Technical University',
    shortName: 'CCTU',
    region: 'Central',
    city: 'Cape Coast',
    type: 'technical',
    established: 1984,
    website: 'cctu.edu.gh',
    colors: { primary: '#0277BD', secondary: '#FFD700' },
  },
  {
    slug: 'takoradi-tu',
    name: 'Takoradi Technical University',
    shortName: 'TTU',
    region: 'Western',
    city: 'Takoradi',
    type: 'technical',
    established: 1954,
    website: 'ttu.edu.gh',
    colors: { primary: '#1B5E20', secondary: '#FFD700' },
  },
  {
    slug: 'ho-tu',
    name: 'Ho Technical University',
    shortName: 'HTU',
    region: 'Volta',
    city: 'Ho',
    type: 'technical',
    established: 1968,
    website: 'htu.edu.gh',
    colors: { primary: '#004D40', secondary: '#FFECB3' },
  },
  {
    slug: 'koforidua-tu',
    name: 'Koforidua Technical University',
    shortName: 'KTU',
    region: 'Eastern',
    city: 'Koforidua',
    type: 'technical',
    established: 1997,
    website: 'ktu.edu.gh',
    colors: { primary: '#E65100', secondary: '#FFF9C4' },
  },
  {
    slug: 'sunyani-tu',
    name: 'Sunyani Technical University',
    shortName: 'STU',
    region: 'Bono',
    city: 'Sunyani',
    type: 'technical',
    established: 1963,
    website: 'stu.edu.gh',
    colors: { primary: '#0D47A1', secondary: '#FFD700' },
  },
  {
    slug: 'wa-tu',
    name: 'Wa Technical University',
    shortName: 'WaTU',
    region: 'Upper West',
    city: 'Wa',
    type: 'technical',
    established: 2016,
    website: 'wtu.edu.gh',
    colors: { primary: '#4E342E', secondary: '#FFCC80' },
  },
  {
    slug: 'bolgatanga-tu',
    name: 'Bolgatanga Technical University',
    shortName: 'BTU',
    region: 'Upper East',
    city: 'Bolgatanga',
    type: 'technical',
    established: 2016,
    website: 'btu.edu.gh',
    colors: { primary: '#C62828', secondary: '#FFD700' },
  },
  {
    slug: 'tamale-tu',
    name: 'Tamale Technical University',
    shortName: 'TaTU',
    region: 'Northern',
    city: 'Tamale',
    type: 'technical',
    established: 1951,
    website: 'tatu.edu.gh',
    colors: { primary: '#006064', secondary: '#FFD700' },
  },

  // ─── Major Private Universities ──────────────────────────────────────────────
  {
    slug: 'ashesi',
    name: 'Ashesi University',
    shortName: 'Ashesi',
    region: 'Eastern',
    city: 'Berekuso',
    type: 'private',
    established: 2002,
    website: 'ashesi.edu.gh',
    colors: { primary: '#8B1A1A', secondary: '#DAA520' },
  },
  {
    slug: 'central-university',
    name: 'Central University',
    shortName: 'CU',
    region: 'Greater Accra',
    city: 'Miotso, Accra',
    type: 'private',
    established: 1988,
    website: 'central.edu.gh',
    colors: { primary: '#4A148C', secondary: '#FFD700' },
  },
  {
    slug: 'ghana-christian',
    name: 'Ghana Christian University College',
    shortName: 'GCUC',
    region: 'Greater Accra',
    city: 'Kwabenya, Accra',
    type: 'private',
    established: 1996,
    website: 'gcuc.edu.gh',
    colors: { primary: '#1A237E', secondary: '#FFD700' },
  },
  {
    slug: 'pentecost-university',
    name: 'Pentecost University',
    shortName: 'PU',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2003,
    website: 'pentvars.edu.gh',
    colors: { primary: '#880E4F', secondary: '#FFD700' },
  },
  {
    slug: 'valley-view',
    name: 'Valley View University',
    shortName: 'VVU',
    region: 'Eastern',
    city: 'Techiman',
    type: 'private',
    established: 1997,
    website: 'vvu.edu.gh',
    colors: { primary: '#2E7D32', secondary: '#81D4FA' },
  },
  {
    slug: 'wisconsin-international',
    name: 'Wisconsin International University College',
    shortName: 'WIUC',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2000,
    website: 'wiuc-ghana.edu.gh',
    colors: { primary: '#1565C0', secondary: '#FFD700' },
  },
  {
    slug: 'regent-university',
    name: 'Regent University College of Science and Technology',
    shortName: 'Regent',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2003,
    website: 'regent.edu.gh',
    colors: { primary: '#0D47A1', secondary: '#FFD700' },
  },
  {
    slug: 'blue-crest',
    name: 'BlueCrest University College',
    shortName: 'BCUC',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2003,
    website: 'bluecrestcollege.com',
    colors: { primary: '#1565C0', secondary: '#E3F2FD' },
  },
  {
    slug: 'methodist-university',
    name: 'Methodist University',
    shortName: 'MU',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2000,
    website: 'mu.edu.gh',
    colors: { primary: '#1A237E', secondary: '#DAA520' },
  },
  {
    slug: 'presbyterian-university',
    name: 'Presbyterian University College',
    shortName: 'PUC',
    region: 'Eastern',
    city: 'Abetifi',
    type: 'private',
    established: 2003,
    website: 'presbyuniversity.edu.gh',
    colors: { primary: '#003087', secondary: '#C8A951' },
  },
  {
    slug: 'catholic-university',
    name: 'Catholic University College of Ghana',
    shortName: 'CUCG',
    region: 'Bono',
    city: 'Fiapre, Sunyani',
    type: 'private',
    established: 2003,
    website: 'cug.edu.gh',
    colors: { primary: '#7B5800', secondary: '#FFD700' },
  },
  {
    slug: 'ghana-telecom-university',
    name: 'Ghana Communication Technology University',
    shortName: 'GCTU',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2012,
    website: 'gctu.edu.gh',
    colors: { primary: '#E65100', secondary: '#FFF9C4' },
  },
  {
    slug: 'islamic-university',
    name: 'Islamic University College Ghana',
    shortName: 'IUG',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 1997,
    website: 'iug.edu.gh',
    colors: { primary: '#1B5E20', secondary: '#C8E6C9' },
  },
  {
    slug: 'sterling-university',
    name: 'Sterling University College',
    shortName: 'Sterling',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2012,
    colors: { primary: '#546E7A', secondary: '#CFD8DC' },
  },
  {
    slug: 'academic-city',
    name: 'Academic City University College',
    shortName: 'ACity',
    region: 'Greater Accra',
    city: 'Haatso, Accra',
    type: 'private',
    established: 2016,
    website: 'academiccity.edu.gh',
    colors: { primary: '#0288D1', secondary: '#E1F5FE' },
  },
  {
    slug: 'ghana-institute-journalism',
    name: 'Ghana Institute of Journalism',
    shortName: 'GIJ',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 1959,
    website: 'gij.edu.gh',
    colors: { primary: '#BF360C', secondary: '#FFF3E0' },
  },
  {
    slug: 'ghana-institute-management',
    name: 'Ghana Institute of Management and Public Administration',
    shortName: 'GIMPA',
    region: 'Greater Accra',
    city: 'Greenhill, Accra',
    type: 'public',
    established: 1961,
    website: 'gimpa.edu.gh',
    colors: { primary: '#111111', secondary: '#DAA520' },
  },
  {
    slug: 'lancaster-ghana',
    name: 'Lancaster University Ghana',
    shortName: 'LU Ghana',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 2013,
    website: 'lancaster.edu.gh',
    colors: { primary: '#B71C1C', secondary: '#FFCDD2' },
  },
  {
    slug: 'ipmc',
    name: 'IPMC College of Technology',
    shortName: 'IPMC',
    region: 'Greater Accra',
    city: 'Accra',
    type: 'private',
    established: 1996,
    website: 'ipmcgh.com',
    colors: { primary: '#01579B', secondary: '#E1F5FE' },
  },
  {
    slug: 'garden-city-university',
    name: 'Garden City University College',
    shortName: 'GCUC',
    region: 'Ashanti',
    city: 'Kumasi',
    type: 'private',
    established: 2003,
    website: 'gcuc.edu.gh',
    colors: { primary: '#2E7D32', secondary: '#C8E6C9' },
  },
]

/** Look up a university by slug */
export function getUniversityBySlug(slug: string): GhanaUniversity | undefined {
  return GHANA_UNIVERSITIES.find(u => u.slug === slug)
}

/** Get all universities of a given type */
export function getUniversitiesByType(type: UniversityType): GhanaUniversity[] {
  return GHANA_UNIVERSITIES.filter(u => u.type === type)
}

/** Get all universities in a region */
export function getUniversitiesByRegion(region: string): GhanaUniversity[] {
  return GHANA_UNIVERSITIES.filter(u => u.region === region)
}

/** All unique Ghana regions that have universities */
export const GHANA_REGIONS_WITH_UNIS = [
  ...new Set(GHANA_UNIVERSITIES.map(u => u.region)),
].sort()
